[package]
name = "my_rust_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lean-sys = { version = "0.0.5", features = ["small_allocator"], default-features = false }